### ISSUE TITLE
建立websocket连接后公众号服务器有一段时间处于僵直状态，会导致ws排队失败

### ISSUE THREAD

**Issue by wangtaohhh** [xiaodouu/gotolibrary_websockets#4]
我不是CS专业的，但是就像title里边描述的那样，想问问大家有没有遇到过这种情况？
报错如下
Traceback (most recent call last):
  File "c:/Users/14918/Desktop/libraryserver/2022_websocketlibary.py", line 46, in <module>
    a = ws.recv()
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_core.py", line 362, in recv
    opcode, data = self.recv_data()
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_core.py", line 385, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_abnf.py", line 337, in recv_frame
    self.recv_header()
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_abnf.py", line 293, in recv_header
    header = self.recv_strict(2)
    bytes_ = self.recv(min(16384, shortage))
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "C:\Users\14918\PycharmProjects\library\venv\Desktop\lib\site-packages\websocket\_socket.py", line 126, in recv
    "Connection to remote host was lost.")
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

**Comment by wangtaohhh** [comment]
已解决
